### ISSUE TITLE
Could you provide an example from the AMI dataset?

### ISSUE THREAD

**Issue by teinhonglo** [Jinhyeong-Lim/Summ-N-ECS#1]
Thank you for releasing the code.
Could you provide an example from the AMI dataset?

Thanks in advance,
Tien-Hong

**Comment by Jinhyeong-Lim** [comment]
I apologize for the late response.

I am currently unable to access the server from the institution where I conducted my research. 
As a result, I can't provide the dataset as you requested. 

However, if you download the dataset from the link provided in the repository's README and use the [pre-processing code](https://github.com/Jinhyeong-Lim/Summ-N-ECS/tree/main/dataset_loader),pre-processing code you should be able to easily reproduce the AMI data.

Thank you
